#!/bin/bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure the redirection
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Restart Nginx
sudo service nginx restart
